{% set version = '1.25' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mutsigextractor
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/UMCUGenetics/mutSigExtractor
  git_tag: 1.25

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: BSgenome.Hsapiens.UCSC.hg19, NNLM, reshape2, ggplot2, stringr
requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - bioconductor-bsgenome
    - bioconductor-genomeinfodb
    - bioconductor-iranges

  run:
    - r-base
    - bioconductor-bsgenome
    - bioconductor-genomeinfodb
    - bioconductor-iranges

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mutSigExtractor')"           # [not win]
    - "\"%R%\" -e \"library('mutSigExtractor')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/UMCUGenetics/mutSigExtractor
  license: GPL3
  summary: Extracts SNV, indel, DBS, and SV signatures from vcf files.

  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: mutSigExtractor
# Type: Package
# Title: Extracts SNV, indel, DBS, and SV signatures from vcf files.
# Version: 1.25
# Author: Luan Nguyen
# Maintainer: Luan N. Nguyen <n.l.nguyen-2@umcutrecht.nl>
# Description: Extracts SNV, indel, DBS, and SV signatures from vcf files.
# License: GPL3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.1
# biocViews:
# Depends: R (>= 3.5.0)
# Imports: BSgenome, GenomeInfoDb, IRanges
# Suggests: BSgenome.Hsapiens.UCSC.hg19, NNLM, reshape2, ggplot2, stringr

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
